name: xon1c · Thomas Nägele's thoughts and work
markdown: redcarpet
pygments: true

# Setup permalinks
permalink: /articles/:title/

# Setup page navigation
navigation:
- text: Work
  url: /work/
  real_url: /work/index.html
- text: Articles
  url: /articles/
  real_url: /articles/index.html
  layout: post
