# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: xon1c · Thomas Nägele · Senior UX Designer
description: I'm a Berlin-based freelance senior user experience designer with a masters degree in computer science and 8 years of hands-on working experience.
baseurl: ""
url: http://xon1c.com
email: tom@naegele.it
twitter_username: "@xon1c"

# Setup permalinks
permalink: /articles/:title/

# Setup page navigation
navigation:
- text: About Me
  url: /
- text: Process
  url: /process/
- text: Skills
  url: /skills/

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - gulpfile.babel.js
  - README.md
  - _tasks
  - _assets
  - node_modules

#Files generated by Gulp
keep_files:
  - assets

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
